// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// ActivateLicenseReader is a Reader for the ActivateLicense structure.
type ActivateLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivateLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewActivateLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/server.license.kubesphere.io/v1alpha1/licenses] ActivateLicense", response, response.Code())
	}
}

// NewActivateLicenseOK creates a ActivateLicenseOK with default headers values
func NewActivateLicenseOK() *ActivateLicenseOK {
	return &ActivateLicenseOK{}
}

/*
ActivateLicenseOK describes a response with status code 200, with default header values.

ok
*/
type ActivateLicenseOK struct {
	Payload *models.ModelsLicenseQuota
}

// IsSuccess returns true when this activate license o k response has a 2xx status code
func (o *ActivateLicenseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this activate license o k response has a 3xx status code
func (o *ActivateLicenseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this activate license o k response has a 4xx status code
func (o *ActivateLicenseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this activate license o k response has a 5xx status code
func (o *ActivateLicenseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this activate license o k response a status code equal to that given
func (o *ActivateLicenseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the activate license o k response
func (o *ActivateLicenseOK) Code() int {
	return 200
}

func (o *ActivateLicenseOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/server.license.kubesphere.io/v1alpha1/licenses][%d] activateLicenseOK %s", 200, payload)
}

func (o *ActivateLicenseOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/server.license.kubesphere.io/v1alpha1/licenses][%d] activateLicenseOK %s", 200, payload)
}

func (o *ActivateLicenseOK) GetPayload() *models.ModelsLicenseQuota {
	return o.Payload
}

func (o *ActivateLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsLicenseQuota)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
