// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// NewDeactivateLicenseParams creates a new DeactivateLicenseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeactivateLicenseParams() *DeactivateLicenseParams {
	return &DeactivateLicenseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeactivateLicenseParamsWithTimeout creates a new DeactivateLicenseParams object
// with the ability to set a timeout on a request.
func NewDeactivateLicenseParamsWithTimeout(timeout time.Duration) *DeactivateLicenseParams {
	return &DeactivateLicenseParams{
		timeout: timeout,
	}
}

// NewDeactivateLicenseParamsWithContext creates a new DeactivateLicenseParams object
// with the ability to set a context for a request.
func NewDeactivateLicenseParamsWithContext(ctx context.Context) *DeactivateLicenseParams {
	return &DeactivateLicenseParams{
		Context: ctx,
	}
}

// NewDeactivateLicenseParamsWithHTTPClient creates a new DeactivateLicenseParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeactivateLicenseParamsWithHTTPClient(client *http.Client) *DeactivateLicenseParams {
	return &DeactivateLicenseParams{
		HTTPClient: client,
	}
}

/*
DeactivateLicenseParams contains all the parameters to send to the API endpoint

	for the deactivate license operation.

	Typically these are written to a http.Request.
*/
type DeactivateLicenseParams struct {

	// Body.
	Body *models.ModelsDeactivateLicenseRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the deactivate license params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeactivateLicenseParams) WithDefaults() *DeactivateLicenseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the deactivate license params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeactivateLicenseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the deactivate license params
func (o *DeactivateLicenseParams) WithTimeout(timeout time.Duration) *DeactivateLicenseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deactivate license params
func (o *DeactivateLicenseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deactivate license params
func (o *DeactivateLicenseParams) WithContext(ctx context.Context) *DeactivateLicenseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deactivate license params
func (o *DeactivateLicenseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deactivate license params
func (o *DeactivateLicenseParams) WithHTTPClient(client *http.Client) *DeactivateLicenseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deactivate license params
func (o *DeactivateLicenseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the deactivate license params
func (o *DeactivateLicenseParams) WithBody(body *models.ModelsDeactivateLicenseRequest) *DeactivateLicenseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the deactivate license params
func (o *DeactivateLicenseParams) SetBody(body *models.ModelsDeactivateLicenseRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeactivateLicenseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
