// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeactivateLicenseReader is a Reader for the DeactivateLicense structure.
type DeactivateLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeactivateLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeactivateLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/licenses] DeactivateLicense", response, response.Code())
	}
}

// NewDeactivateLicenseOK creates a DeactivateLicenseOK with default headers values
func NewDeactivateLicenseOK() *DeactivateLicenseOK {
	return &DeactivateLicenseOK{}
}

/*
DeactivateLicenseOK describes a response with status code 200, with default header values.

ok
*/
type DeactivateLicenseOK struct {
}

// IsSuccess returns true when this deactivate license o k response has a 2xx status code
func (o *DeactivateLicenseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this deactivate license o k response has a 3xx status code
func (o *DeactivateLicenseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this deactivate license o k response has a 4xx status code
func (o *DeactivateLicenseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this deactivate license o k response has a 5xx status code
func (o *DeactivateLicenseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this deactivate license o k response a status code equal to that given
func (o *DeactivateLicenseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the deactivate license o k response
func (o *DeactivateLicenseOK) Code() int {
	return 200
}

func (o *DeactivateLicenseOK) Error() string {
	return fmt.Sprintf("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/licenses][%d] deactivateLicenseOK", 200)
}

func (o *DeactivateLicenseOK) String() string {
	return fmt.Sprintf("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/licenses][%d] deactivateLicenseOK", 200)
}

func (o *DeactivateLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
