// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new license management API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new license management API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new license management API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for license management API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextPlain sets the Accept header to "text/plain".
func WithAcceptTextPlain(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	ActivateLicense(params *ActivateLicenseParams, opts ...ClientOption) (*ActivateLicenseOK, error)

	DeactivateLicense(params *DeactivateLicenseParams, opts ...ClientOption) (*DeactivateLicenseOK, error)

	GetInfo(params *GetInfoParams, opts ...ClientOption) (*GetInfoOK, error)

	ListLicenseLeases(params *ListLicenseLeasesParams, opts ...ClientOption) (*ListLicenseLeasesOK, error)

	ListQuotaUsages(params *ListQuotaUsagesParams, opts ...ClientOption) (*ListQuotaUsagesOK, error)

	Ping(params *PingParams, opts ...ClientOption) (*PingOK, error)

	ReclaimLicenseLease(params *ReclaimLicenseLeaseParams, opts ...ClientOption) (*ReclaimLicenseLeaseOK, error)

	RequestLicenseLease(params *RequestLicenseLeaseParams, opts ...ClientOption) (*RequestLicenseLeaseOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ActivateLicense activates a license
*/
func (a *Client) ActivateLicense(params *ActivateLicenseParams, opts ...ClientOption) (*ActivateLicenseOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewActivateLicenseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ActivateLicense",
		Method:             "POST",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/licenses",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ActivateLicenseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ActivateLicenseOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ActivateLicense: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeactivateLicense deactivates a license
*/
func (a *Client) DeactivateLicense(params *DeactivateLicenseParams, opts ...ClientOption) (*DeactivateLicenseOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeactivateLicenseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeactivateLicense",
		Method:             "DELETE",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/licenses",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeactivateLicenseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeactivateLicenseOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeactivateLicense: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetInfo gets server information
*/
func (a *Client) GetInfo(params *GetInfoParams, opts ...ClientOption) (*GetInfoOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetInfoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetInfo",
		Method:             "GET",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/info",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetInfoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetInfoOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetInfo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListLicenseLeases lists license leases acquired by the cluster
*/
func (a *Client) ListLicenseLeases(params *ListLicenseLeasesParams, opts ...ClientOption) (*ListLicenseLeasesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListLicenseLeasesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListLicenseLeases",
		Method:             "GET",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListLicenseLeasesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListLicenseLeasesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListLicenseLeases: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListQuotaUsages lists license quota and usage
*/
func (a *Client) ListQuotaUsages(params *ListQuotaUsagesParams, opts ...ClientOption) (*ListQuotaUsagesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListQuotaUsagesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListQuotaUsages",
		Method:             "GET",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/quotas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListQuotaUsagesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListQuotaUsagesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListQuotaUsages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
Ping pings by cluster
*/
func (a *Client) Ping(params *PingParams, opts ...ClientOption) (*PingOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPingParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Ping",
		Method:             "GET",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/ping",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PingOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Ping: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ReclaimLicenseLease reclaims license leases acquired by the cluster
*/
func (a *Client) ReclaimLicenseLease(params *ReclaimLicenseLeaseParams, opts ...ClientOption) (*ReclaimLicenseLeaseOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewReclaimLicenseLeaseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReclaimLicenseLease",
		Method:             "DELETE",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ReclaimLicenseLeaseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ReclaimLicenseLeaseOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ReclaimLicenseLease: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RequestLicenseLease requests a license lease for cluster
*/
func (a *Client) RequestLicenseLease(params *RequestLicenseLeaseParams, opts ...ClientOption) (*RequestLicenseLeaseOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRequestLicenseLeaseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RequestLicenseLease",
		Method:             "POST",
		PathPattern:        "/kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RequestLicenseLeaseReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RequestLicenseLeaseOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RequestLicenseLease: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
