// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// ListQuotaUsagesReader is a Reader for the ListQuotaUsages structure.
type ListQuotaUsagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListQuotaUsagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListQuotaUsagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/server.license.kubesphere.io/v1alpha1/quotas] ListQuotaUsages", response, response.Code())
	}
}

// NewListQuotaUsagesOK creates a ListQuotaUsagesOK with default headers values
func NewListQuotaUsagesOK() *ListQuotaUsagesOK {
	return &ListQuotaUsagesOK{}
}

/*
ListQuotaUsagesOK describes a response with status code 200, with default header values.

ok
*/
type ListQuotaUsagesOK struct {
	Payload []*models.ModelsQuotaUsage
}

// IsSuccess returns true when this list quota usages o k response has a 2xx status code
func (o *ListQuotaUsagesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list quota usages o k response has a 3xx status code
func (o *ListQuotaUsagesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list quota usages o k response has a 4xx status code
func (o *ListQuotaUsagesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list quota usages o k response has a 5xx status code
func (o *ListQuotaUsagesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list quota usages o k response a status code equal to that given
func (o *ListQuotaUsagesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list quota usages o k response
func (o *ListQuotaUsagesOK) Code() int {
	return 200
}

func (o *ListQuotaUsagesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/server.license.kubesphere.io/v1alpha1/quotas][%d] listQuotaUsagesOK %s", 200, payload)
}

func (o *ListQuotaUsagesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/server.license.kubesphere.io/v1alpha1/quotas][%d] listQuotaUsagesOK %s", 200, payload)
}

func (o *ListQuotaUsagesOK) GetPayload() []*models.ModelsQuotaUsage {
	return o.Payload
}

func (o *ListQuotaUsagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
