// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListLicenseLeasesParams creates a new ListLicenseLeasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListLicenseLeasesParams() *ListLicenseLeasesParams {
	return &ListLicenseLeasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListLicenseLeasesParamsWithTimeout creates a new ListLicenseLeasesParams object
// with the ability to set a timeout on a request.
func NewListLicenseLeasesParamsWithTimeout(timeout time.Duration) *ListLicenseLeasesParams {
	return &ListLicenseLeasesParams{
		timeout: timeout,
	}
}

// NewListLicenseLeasesParamsWithContext creates a new ListLicenseLeasesParams object
// with the ability to set a context for a request.
func NewListLicenseLeasesParamsWithContext(ctx context.Context) *ListLicenseLeasesParams {
	return &ListLicenseLeasesParams{
		Context: ctx,
	}
}

// NewListLicenseLeasesParamsWithHTTPClient creates a new ListLicenseLeasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListLicenseLeasesParamsWithHTTPClient(client *http.Client) *ListLicenseLeasesParams {
	return &ListLicenseLeasesParams{
		HTTPClient: client,
	}
}

/*
ListLicenseLeasesParams contains all the parameters to send to the API endpoint

	for the list license leases operation.

	Typically these are written to a http.Request.
*/
type ListLicenseLeasesParams struct {

	/* Cluster.

	   cluster id
	*/
	Cluster string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list license leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListLicenseLeasesParams) WithDefaults() *ListLicenseLeasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list license leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListLicenseLeasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list license leases params
func (o *ListLicenseLeasesParams) WithTimeout(timeout time.Duration) *ListLicenseLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list license leases params
func (o *ListLicenseLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list license leases params
func (o *ListLicenseLeasesParams) WithContext(ctx context.Context) *ListLicenseLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list license leases params
func (o *ListLicenseLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list license leases params
func (o *ListLicenseLeasesParams) WithHTTPClient(client *http.Client) *ListLicenseLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list license leases params
func (o *ListLicenseLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the list license leases params
func (o *ListLicenseLeasesParams) WithCluster(cluster string) *ListLicenseLeasesParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the list license leases params
func (o *ListLicenseLeasesParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WriteToRequest writes these params to a swagger request
func (o *ListLicenseLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
