// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListQuotaUsagesParams creates a new ListQuotaUsagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListQuotaUsagesParams() *ListQuotaUsagesParams {
	return &ListQuotaUsagesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListQuotaUsagesParamsWithTimeout creates a new ListQuotaUsagesParams object
// with the ability to set a timeout on a request.
func NewListQuotaUsagesParamsWithTimeout(timeout time.Duration) *ListQuotaUsagesParams {
	return &ListQuotaUsagesParams{
		timeout: timeout,
	}
}

// NewListQuotaUsagesParamsWithContext creates a new ListQuotaUsagesParams object
// with the ability to set a context for a request.
func NewListQuotaUsagesParamsWithContext(ctx context.Context) *ListQuotaUsagesParams {
	return &ListQuotaUsagesParams{
		Context: ctx,
	}
}

// NewListQuotaUsagesParamsWithHTTPClient creates a new ListQuotaUsagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListQuotaUsagesParamsWithHTTPClient(client *http.Client) *ListQuotaUsagesParams {
	return &ListQuotaUsagesParams{
		HTTPClient: client,
	}
}

/*
ListQuotaUsagesParams contains all the parameters to send to the API endpoint

	for the list quota usages operation.

	Typically these are written to a http.Request.
*/
type ListQuotaUsagesParams struct {

	/* Bundle.

	   bundle name to query, default to all bundles.
	*/
	Bundle *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list quota usages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListQuotaUsagesParams) WithDefaults() *ListQuotaUsagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list quota usages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListQuotaUsagesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list quota usages params
func (o *ListQuotaUsagesParams) WithTimeout(timeout time.Duration) *ListQuotaUsagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list quota usages params
func (o *ListQuotaUsagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list quota usages params
func (o *ListQuotaUsagesParams) WithContext(ctx context.Context) *ListQuotaUsagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list quota usages params
func (o *ListQuotaUsagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list quota usages params
func (o *ListQuotaUsagesParams) WithHTTPClient(client *http.Client) *ListQuotaUsagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list quota usages params
func (o *ListQuotaUsagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBundle adds the bundle to the list quota usages params
func (o *ListQuotaUsagesParams) WithBundle(bundle *string) *ListQuotaUsagesParams {
	o.SetBundle(bundle)
	return o
}

// SetBundle adds the bundle to the list quota usages params
func (o *ListQuotaUsagesParams) SetBundle(bundle *string) {
	o.Bundle = bundle
}

// WriteToRequest writes these params to a swagger request
func (o *ListQuotaUsagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Bundle != nil {

		// query param bundle
		var qrBundle string

		if o.Bundle != nil {
			qrBundle = *o.Bundle
		}
		qBundle := qrBundle
		if qBundle != "" {

			if err := r.SetQueryParam("bundle", qBundle); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
