// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// ListAllLeasesReader is a Reader for the ListAllLeases structure.
type ListAllLeasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllLeasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListAllLeasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/server.license.kubesphere.io/v1alpha1/leases] ListAllLeases", response, response.Code())
	}
}

// NewListAllLeasesOK creates a ListAllLeasesOK with default headers values
func NewListAllLeasesOK() *ListAllLeasesOK {
	return &ListAllLeasesOK{}
}

/*
ListAllLeasesOK describes a response with status code 200, with default header values.

ok
*/
type ListAllLeasesOK struct {
	Payload []*models.ModelsLicenseLease
}

// IsSuccess returns true when this list all leases o k response has a 2xx status code
func (o *ListAllLeasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list all leases o k response has a 3xx status code
func (o *ListAllLeasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list all leases o k response has a 4xx status code
func (o *ListAllLeasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list all leases o k response has a 5xx status code
func (o *ListAllLeasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list all leases o k response a status code equal to that given
func (o *ListAllLeasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list all leases o k response
func (o *ListAllLeasesOK) Code() int {
	return 200
}

func (o *ListAllLeasesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/server.license.kubesphere.io/v1alpha1/leases][%d] listAllLeasesOK %s", 200, payload)
}

func (o *ListAllLeasesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/server.license.kubesphere.io/v1alpha1/leases][%d] listAllLeasesOK %s", 200, payload)
}

func (o *ListAllLeasesOK) GetPayload() []*models.ModelsLicenseLease {
	return o.Payload
}

func (o *ListAllLeasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
