// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAllLeasesParams creates a new ListAllLeasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListAllLeasesParams() *ListAllLeasesParams {
	return &ListAllLeasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListAllLeasesParamsWithTimeout creates a new ListAllLeasesParams object
// with the ability to set a timeout on a request.
func NewListAllLeasesParamsWithTimeout(timeout time.Duration) *ListAllLeasesParams {
	return &ListAllLeasesParams{
		timeout: timeout,
	}
}

// NewListAllLeasesParamsWithContext creates a new ListAllLeasesParams object
// with the ability to set a context for a request.
func NewListAllLeasesParamsWithContext(ctx context.Context) *ListAllLeasesParams {
	return &ListAllLeasesParams{
		Context: ctx,
	}
}

// NewListAllLeasesParamsWithHTTPClient creates a new ListAllLeasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListAllLeasesParamsWithHTTPClient(client *http.Client) *ListAllLeasesParams {
	return &ListAllLeasesParams{
		HTTPClient: client,
	}
}

/*
ListAllLeasesParams contains all the parameters to send to the API endpoint

	for the list all leases operation.

	Typically these are written to a http.Request.
*/
type ListAllLeasesParams struct {

	/* Cluster.

	   cluster id to filter, can be specified multiple times.
	*/
	Cluster *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list all leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAllLeasesParams) WithDefaults() *ListAllLeasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list all leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListAllLeasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list all leases params
func (o *ListAllLeasesParams) WithTimeout(timeout time.Duration) *ListAllLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all leases params
func (o *ListAllLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all leases params
func (o *ListAllLeasesParams) WithContext(ctx context.Context) *ListAllLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all leases params
func (o *ListAllLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all leases params
func (o *ListAllLeasesParams) WithHTTPClient(client *http.Client) *ListAllLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all leases params
func (o *ListAllLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the list all leases params
func (o *ListAllLeasesParams) WithCluster(cluster *string) *ListAllLeasesParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the list all leases params
func (o *ListAllLeasesParams) SetCluster(cluster *string) {
	o.Cluster = cluster
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cluster != nil {

		// query param cluster
		var qrCluster string

		if o.Cluster != nil {
			qrCluster = *o.Cluster
		}
		qCluster := qrCluster
		if qCluster != "" {

			if err := r.SetQueryParam("cluster", qCluster); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
