// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// ListLicenseLeasesReader is a Reader for the ListLicenseLeases structure.
type ListLicenseLeasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListLicenseLeasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListLicenseLeasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases] ListLicenseLeases", response, response.Code())
	}
}

// NewListLicenseLeasesOK creates a ListLicenseLeasesOK with default headers values
func NewListLicenseLeasesOK() *ListLicenseLeasesOK {
	return &ListLicenseLeasesOK{}
}

/*
ListLicenseLeasesOK describes a response with status code 200, with default header values.

ok
*/
type ListLicenseLeasesOK struct {
	Payload []*models.ModelsLicenseLease
}

// IsSuccess returns true when this list license leases o k response has a 2xx status code
func (o *ListLicenseLeasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list license leases o k response has a 3xx status code
func (o *ListLicenseLeasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list license leases o k response has a 4xx status code
func (o *ListLicenseLeasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list license leases o k response has a 5xx status code
func (o *ListLicenseLeasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list license leases o k response a status code equal to that given
func (o *ListLicenseLeasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list license leases o k response
func (o *ListLicenseLeasesOK) Code() int {
	return 200
}

func (o *ListLicenseLeasesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases][%d] listLicenseLeasesOK %s", 200, payload)
}

func (o *ListLicenseLeasesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases][%d] listLicenseLeasesOK %s", 200, payload)
}

func (o *ListLicenseLeasesOK) GetPayload() []*models.ModelsLicenseLease {
	return o.Payload
}

func (o *ListLicenseLeasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
