// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReclaimLicenseLeaseParams creates a new ReclaimLicenseLeaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReclaimLicenseLeaseParams() *ReclaimLicenseLeaseParams {
	return &ReclaimLicenseLeaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReclaimLicenseLeaseParamsWithTimeout creates a new ReclaimLicenseLeaseParams object
// with the ability to set a timeout on a request.
func NewReclaimLicenseLeaseParamsWithTimeout(timeout time.Duration) *ReclaimLicenseLeaseParams {
	return &ReclaimLicenseLeaseParams{
		timeout: timeout,
	}
}

// NewReclaimLicenseLeaseParamsWithContext creates a new ReclaimLicenseLeaseParams object
// with the ability to set a context for a request.
func NewReclaimLicenseLeaseParamsWithContext(ctx context.Context) *ReclaimLicenseLeaseParams {
	return &ReclaimLicenseLeaseParams{
		Context: ctx,
	}
}

// NewReclaimLicenseLeaseParamsWithHTTPClient creates a new ReclaimLicenseLeaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewReclaimLicenseLeaseParamsWithHTTPClient(client *http.Client) *ReclaimLicenseLeaseParams {
	return &ReclaimLicenseLeaseParams{
		HTTPClient: client,
	}
}

/*
ReclaimLicenseLeaseParams contains all the parameters to send to the API endpoint

	for the reclaim license lease operation.

	Typically these are written to a http.Request.
*/
type ReclaimLicenseLeaseParams struct {

	/* Cluster.

	   cluster id
	*/
	Cluster string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reclaim license lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReclaimLicenseLeaseParams) WithDefaults() *ReclaimLicenseLeaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reclaim license lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReclaimLicenseLeaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) WithTimeout(timeout time.Duration) *ReclaimLicenseLeaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) WithContext(ctx context.Context) *ReclaimLicenseLeaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) WithHTTPClient(client *http.Client) *ReclaimLicenseLeaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) WithCluster(cluster string) *ReclaimLicenseLeaseParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the reclaim license lease params
func (o *ReclaimLicenseLeaseParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WriteToRequest writes these params to a swagger request
func (o *ReclaimLicenseLeaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
