// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReclaimAllLeasesParams creates a new ReclaimAllLeasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReclaimAllLeasesParams() *ReclaimAllLeasesParams {
	return &ReclaimAllLeasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReclaimAllLeasesParamsWithTimeout creates a new ReclaimAllLeasesParams object
// with the ability to set a timeout on a request.
func NewReclaimAllLeasesParamsWithTimeout(timeout time.Duration) *ReclaimAllLeasesParams {
	return &ReclaimAllLeasesParams{
		timeout: timeout,
	}
}

// NewReclaimAllLeasesParamsWithContext creates a new ReclaimAllLeasesParams object
// with the ability to set a context for a request.
func NewReclaimAllLeasesParamsWithContext(ctx context.Context) *ReclaimAllLeasesParams {
	return &ReclaimAllLeasesParams{
		Context: ctx,
	}
}

// NewReclaimAllLeasesParamsWithHTTPClient creates a new ReclaimAllLeasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewReclaimAllLeasesParamsWithHTTPClient(client *http.Client) *ReclaimAllLeasesParams {
	return &ReclaimAllLeasesParams{
		HTTPClient: client,
	}
}

/*
ReclaimAllLeasesParams contains all the parameters to send to the API endpoint

	for the reclaim all leases operation.

	Typically these are written to a http.Request.
*/
type ReclaimAllLeasesParams struct {

	/* Cluster.

	   cluster id to filter, can be specified multiple times.
	*/
	Cluster *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reclaim all leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReclaimAllLeasesParams) WithDefaults() *ReclaimAllLeasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reclaim all leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReclaimAllLeasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reclaim all leases params
func (o *ReclaimAllLeasesParams) WithTimeout(timeout time.Duration) *ReclaimAllLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reclaim all leases params
func (o *ReclaimAllLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reclaim all leases params
func (o *ReclaimAllLeasesParams) WithContext(ctx context.Context) *ReclaimAllLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reclaim all leases params
func (o *ReclaimAllLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reclaim all leases params
func (o *ReclaimAllLeasesParams) WithHTTPClient(client *http.Client) *ReclaimAllLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reclaim all leases params
func (o *ReclaimAllLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the reclaim all leases params
func (o *ReclaimAllLeasesParams) WithCluster(cluster *string) *ReclaimAllLeasesParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the reclaim all leases params
func (o *ReclaimAllLeasesParams) SetCluster(cluster *string) {
	o.Cluster = cluster
}

// WriteToRequest writes these params to a swagger request
func (o *ReclaimAllLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cluster != nil {

		// query param cluster
		var qrCluster string

		if o.Cluster != nil {
			qrCluster = *o.Cluster
		}
		qCluster := qrCluster
		if qCluster != "" {

			if err := r.SetQueryParam("cluster", qCluster); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
