// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReclaimLicenseLeaseReader is a Reader for the ReclaimLicenseLease structure.
type ReclaimLicenseLeaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReclaimLicenseLeaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewReclaimLicenseLeaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases] ReclaimLicenseLease", response, response.Code())
	}
}

// NewReclaimLicenseLeaseOK creates a ReclaimLicenseLeaseOK with default headers values
func NewReclaimLicenseLeaseOK() *ReclaimLicenseLeaseOK {
	return &ReclaimLicenseLeaseOK{}
}

/*
ReclaimLicenseLeaseOK describes a response with status code 200, with default header values.

ok
*/
type ReclaimLicenseLeaseOK struct {
}

// IsSuccess returns true when this reclaim license lease o k response has a 2xx status code
func (o *ReclaimLicenseLeaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reclaim license lease o k response has a 3xx status code
func (o *ReclaimLicenseLeaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reclaim license lease o k response has a 4xx status code
func (o *ReclaimLicenseLeaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reclaim license lease o k response has a 5xx status code
func (o *ReclaimLicenseLeaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reclaim license lease o k response a status code equal to that given
func (o *ReclaimLicenseLeaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the reclaim license lease o k response
func (o *ReclaimLicenseLeaseOK) Code() int {
	return 200
}

func (o *ReclaimLicenseLeaseOK) Error() string {
	return fmt.Sprintf("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases][%d] reclaimLicenseLeaseOK", 200)
}

func (o *ReclaimLicenseLeaseOK) String() string {
	return fmt.Sprintf("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases][%d] reclaimLicenseLeaseOK", 200)
}

func (o *ReclaimLicenseLeaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
