// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReclaimAllLeasesReader is a Reader for the ReclaimAllLeases structure.
type ReclaimAllLeasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReclaimAllLeasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewReclaimAllLeasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/leases] ReclaimAllLeases", response, response.Code())
	}
}

// NewReclaimAllLeasesOK creates a ReclaimAllLeasesOK with default headers values
func NewReclaimAllLeasesOK() *ReclaimAllLeasesOK {
	return &ReclaimAllLeasesOK{}
}

/*
ReclaimAllLeasesOK describes a response with status code 200, with default header values.

ok
*/
type ReclaimAllLeasesOK struct {
}

// IsSuccess returns true when this reclaim all leases o k response has a 2xx status code
func (o *ReclaimAllLeasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reclaim all leases o k response has a 3xx status code
func (o *ReclaimAllLeasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reclaim all leases o k response has a 4xx status code
func (o *ReclaimAllLeasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this reclaim all leases o k response has a 5xx status code
func (o *ReclaimAllLeasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this reclaim all leases o k response a status code equal to that given
func (o *ReclaimAllLeasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the reclaim all leases o k response
func (o *ReclaimAllLeasesOK) Code() int {
	return 200
}

func (o *ReclaimAllLeasesOK) Error() string {
	return fmt.Sprintf("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/leases][%d] reclaimAllLeasesOK", 200)
}

func (o *ReclaimAllLeasesOK) String() string {
	return fmt.Sprintf("[DELETE /kapis/server.license.kubesphere.io/v1alpha1/leases][%d] reclaimAllLeasesOK", 200)
}

func (o *ReclaimAllLeasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
