// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// NewRequestLicenseLeaseParams creates a new RequestLicenseLeaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRequestLicenseLeaseParams() *RequestLicenseLeaseParams {
	return &RequestLicenseLeaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRequestLicenseLeaseParamsWithTimeout creates a new RequestLicenseLeaseParams object
// with the ability to set a timeout on a request.
func NewRequestLicenseLeaseParamsWithTimeout(timeout time.Duration) *RequestLicenseLeaseParams {
	return &RequestLicenseLeaseParams{
		timeout: timeout,
	}
}

// NewRequestLicenseLeaseParamsWithContext creates a new RequestLicenseLeaseParams object
// with the ability to set a context for a request.
func NewRequestLicenseLeaseParamsWithContext(ctx context.Context) *RequestLicenseLeaseParams {
	return &RequestLicenseLeaseParams{
		Context: ctx,
	}
}

// NewRequestLicenseLeaseParamsWithHTTPClient creates a new RequestLicenseLeaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewRequestLicenseLeaseParamsWithHTTPClient(client *http.Client) *RequestLicenseLeaseParams {
	return &RequestLicenseLeaseParams{
		HTTPClient: client,
	}
}

/*
RequestLicenseLeaseParams contains all the parameters to send to the API endpoint

	for the request license lease operation.

	Typically these are written to a http.Request.
*/
type RequestLicenseLeaseParams struct {

	// Body.
	Body *models.ModelsCreateLicenseLeaseRequest

	/* Cluster.

	   cluster id
	*/
	Cluster string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the request license lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestLicenseLeaseParams) WithDefaults() *RequestLicenseLeaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the request license lease params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestLicenseLeaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the request license lease params
func (o *RequestLicenseLeaseParams) WithTimeout(timeout time.Duration) *RequestLicenseLeaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request license lease params
func (o *RequestLicenseLeaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request license lease params
func (o *RequestLicenseLeaseParams) WithContext(ctx context.Context) *RequestLicenseLeaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request license lease params
func (o *RequestLicenseLeaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request license lease params
func (o *RequestLicenseLeaseParams) WithHTTPClient(client *http.Client) *RequestLicenseLeaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request license lease params
func (o *RequestLicenseLeaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the request license lease params
func (o *RequestLicenseLeaseParams) WithBody(body *models.ModelsCreateLicenseLeaseRequest) *RequestLicenseLeaseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the request license lease params
func (o *RequestLicenseLeaseParams) SetBody(body *models.ModelsCreateLicenseLeaseRequest) {
	o.Body = body
}

// WithCluster adds the cluster to the request license lease params
func (o *RequestLicenseLeaseParams) WithCluster(cluster string) *RequestLicenseLeaseParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the request license lease params
func (o *RequestLicenseLeaseParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WriteToRequest writes these params to a swagger request
func (o *RequestLicenseLeaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
