// Code generated by go-swagger; DO NOT EDIT.

package license_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubesphere/license-server-client-go/api/models"
)

// RequestLicenseLeaseReader is a Reader for the RequestLicenseLease structure.
type RequestLicenseLeaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestLicenseLeaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRequestLicenseLeaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases] RequestLicenseLease", response, response.Code())
	}
}

// NewRequestLicenseLeaseOK creates a RequestLicenseLeaseOK with default headers values
func NewRequestLicenseLeaseOK() *RequestLicenseLeaseOK {
	return &RequestLicenseLeaseOK{}
}

/*
RequestLicenseLeaseOK describes a response with status code 200, with default header values.

ok
*/
type RequestLicenseLeaseOK struct {
	Payload *models.ModelsLicenseLease
}

// IsSuccess returns true when this request license lease o k response has a 2xx status code
func (o *RequestLicenseLeaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this request license lease o k response has a 3xx status code
func (o *RequestLicenseLeaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this request license lease o k response has a 4xx status code
func (o *RequestLicenseLeaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this request license lease o k response has a 5xx status code
func (o *RequestLicenseLeaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this request license lease o k response a status code equal to that given
func (o *RequestLicenseLeaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the request license lease o k response
func (o *RequestLicenseLeaseOK) Code() int {
	return 200
}

func (o *RequestLicenseLeaseOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases][%d] requestLicenseLeaseOK %s", 200, payload)
}

func (o *RequestLicenseLeaseOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kapis/server.license.kubesphere.io/v1alpha1/clusters/{cluster}/leases][%d] requestLicenseLeaseOK %s", 200, payload)
}

func (o *RequestLicenseLeaseOK) GetPayload() *models.ModelsLicenseLease {
	return o.Payload
}

func (o *RequestLicenseLeaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsLicenseLease)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
