// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GormDeletedAt gorm deleted at
//
// swagger:model gorm.DeletedAt
type GormDeletedAt struct {

	// time
	// Required: true
	// Format: date-time
	Time *strfmt.DateTime `json:"Time"`

	// valid
	// Required: true
	Valid *bool `json:"Valid"`
}

// Validate validates this gorm deleted at
func (m *GormDeletedAt) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GormDeletedAt) validateTime(formats strfmt.Registry) error {

	if err := validate.Required("Time", "body", m.Time); err != nil {
		return err
	}

	if err := validate.FormatOf("Time", "body", "date-time", m.Time.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GormDeletedAt) validateValid(formats strfmt.Registry) error {

	if err := validate.Required("Valid", "body", m.Valid); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this gorm deleted at based on context it is used
func (m *GormDeletedAt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GormDeletedAt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GormDeletedAt) UnmarshalBinary(b []byte) error {
	var res GormDeletedAt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
