// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsLicenseLease models license lease
//
// swagger:model models.LicenseLease
type ModelsLicenseLease struct {

	// bundle
	// Required: true
	Bundle *string `json:"Bundle"`

	// bundle raw
	// Required: true
	BundleRaw *string `json:"BundleRaw"`

	// cluster ID
	// Required: true
	ClusterID *string `json:"ClusterID"`

	// created at
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"CreatedAt"`

	// deleted at
	// Required: true
	DeletedAt *GormDeletedAt `json:"DeletedAt"`

	// ID
	// Required: true
	ID *int64 `json:"ID"`

	// license ID
	// Required: true
	LicenseID *string `json:"LicenseID"`

	// not after
	// Required: true
	// Format: date-time
	NotAfter *strfmt.DateTime `json:"NotAfter"`

	// not before
	// Required: true
	// Format: date-time
	NotBefore *strfmt.DateTime `json:"NotBefore"`

	// plan name
	// Required: true
	PlanName *string `json:"PlanName"`

	// plan type
	// Required: true
	PlanType *string `json:"PlanType"`

	// quota
	// Required: true
	Quota *int64 `json:"Quota"`

	// raw
	// Required: true
	Raw *string `json:"Raw"`

	// resource type
	// Required: true
	ResourceType *string `json:"ResourceType"`

	// updated at
	// Required: true
	// Format: date-time
	UpdatedAt *strfmt.DateTime `json:"UpdatedAt"`

	// version
	// Required: true
	Version *string `json:"Version"`
}

// Validate validates this models license lease
func (m *ModelsLicenseLease) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBundle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBundleRaw(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLicenseID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotAfter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotBefore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlanName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlanType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuota(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRaw(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsLicenseLease) validateBundle(formats strfmt.Registry) error {

	if err := validate.Required("Bundle", "body", m.Bundle); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateBundleRaw(formats strfmt.Registry) error {

	if err := validate.Required("BundleRaw", "body", m.BundleRaw); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateClusterID(formats strfmt.Registry) error {

	if err := validate.Required("ClusterID", "body", m.ClusterID); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("CreatedAt", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("CreatedAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateDeletedAt(formats strfmt.Registry) error {

	if err := validate.Required("DeletedAt", "body", m.DeletedAt); err != nil {
		return err
	}

	if m.DeletedAt != nil {
		if err := m.DeletedAt.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("DeletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("DeletedAt")
			}

			return err
		}
	}

	return nil
}

func (m *ModelsLicenseLease) validateID(formats strfmt.Registry) error {

	if err := validate.Required("ID", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateLicenseID(formats strfmt.Registry) error {

	if err := validate.Required("LicenseID", "body", m.LicenseID); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateNotAfter(formats strfmt.Registry) error {

	if err := validate.Required("NotAfter", "body", m.NotAfter); err != nil {
		return err
	}

	if err := validate.FormatOf("NotAfter", "body", "date-time", m.NotAfter.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateNotBefore(formats strfmt.Registry) error {

	if err := validate.Required("NotBefore", "body", m.NotBefore); err != nil {
		return err
	}

	if err := validate.FormatOf("NotBefore", "body", "date-time", m.NotBefore.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validatePlanName(formats strfmt.Registry) error {

	if err := validate.Required("PlanName", "body", m.PlanName); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validatePlanType(formats strfmt.Registry) error {

	if err := validate.Required("PlanType", "body", m.PlanType); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateQuota(formats strfmt.Registry) error {

	if err := validate.Required("Quota", "body", m.Quota); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateRaw(formats strfmt.Registry) error {

	if err := validate.Required("Raw", "body", m.Raw); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateResourceType(formats strfmt.Registry) error {

	if err := validate.Required("ResourceType", "body", m.ResourceType); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("UpdatedAt", "body", m.UpdatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("UpdatedAt", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ModelsLicenseLease) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("Version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this models license lease based on the context it is used
func (m *ModelsLicenseLease) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeletedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsLicenseLease) contextValidateDeletedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.DeletedAt != nil {

		if err := m.DeletedAt.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("DeletedAt")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("DeletedAt")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsLicenseLease) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsLicenseLease) UnmarshalBinary(b []byte) error {
	var res ModelsLicenseLease
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
