// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsDeactivateLicenseRequest models deactivate license request
//
// swagger:model models.DeactivateLicenseRequest
type ModelsDeactivateLicenseRequest struct {

	// all
	// Required: true
	All *bool `json:"all"`

	// bundle
	// Required: true
	Bundle *string `json:"bundle"`
}

// Validate validates this models deactivate license request
func (m *ModelsDeactivateLicenseRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAll(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBundle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsDeactivateLicenseRequest) validateAll(formats strfmt.Registry) error {

	if err := validate.Required("all", "body", m.All); err != nil {
		return err
	}

	return nil
}

func (m *ModelsDeactivateLicenseRequest) validateBundle(formats strfmt.Registry) error {

	if err := validate.Required("bundle", "body", m.Bundle); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this models deactivate license request based on context it is used
func (m *ModelsDeactivateLicenseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsDeactivateLicenseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsDeactivateLicenseRequest) UnmarshalBinary(b []byte) error {
	var res ModelsDeactivateLicenseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
