// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsServerInformation models server information
//
// swagger:model models.ServerInformation
type ModelsServerInformation struct {

	// runtime
	// Required: true
	Runtime *string `json:"Runtime"`

	// server ID
	// Required: true
	ServerID *string `json:"ServerID"`

	// version
	// Required: true
	Version *string `json:"Version"`
}

// Validate validates this models server information
func (m *ModelsServerInformation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuntime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsServerInformation) validateRuntime(formats strfmt.Registry) error {

	if err := validate.Required("Runtime", "body", m.Runtime); err != nil {
		return err
	}

	return nil
}

func (m *ModelsServerInformation) validateServerID(formats strfmt.Registry) error {

	if err := validate.Required("ServerID", "body", m.ServerID); err != nil {
		return err
	}

	return nil
}

func (m *ModelsServerInformation) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("Version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this models server information based on context it is used
func (m *ModelsServerInformation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsServerInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsServerInformation) UnmarshalBinary(b []byte) error {
	var res ModelsServerInformation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
