// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsCreateLicenseLeaseRequest models create license lease request
//
// swagger:model models.CreateLicenseLeaseRequest
type ModelsCreateLicenseLeaseRequest struct {

	// bundle
	// Required: true
	Bundle *string `json:"Bundle"`

	// license version
	// Required: true
	LicenseVersion *string `json:"LicenseVersion"`

	// not after
	// Required: true
	NotAfter *string `json:"NotAfter"`

	// not before
	// Required: true
	NotBefore *string `json:"NotBefore"`

	// vcpu
	// Required: true
	Vcpu *int64 `json:"Vcpu"`
}

// Validate validates this models create license lease request
func (m *ModelsCreateLicenseLeaseRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBundle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLicenseVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotAfter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotBefore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVcpu(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsCreateLicenseLeaseRequest) validateBundle(formats strfmt.Registry) error {

	if err := validate.Required("Bundle", "body", m.Bundle); err != nil {
		return err
	}

	return nil
}

func (m *ModelsCreateLicenseLeaseRequest) validateLicenseVersion(formats strfmt.Registry) error {

	if err := validate.Required("LicenseVersion", "body", m.LicenseVersion); err != nil {
		return err
	}

	return nil
}

func (m *ModelsCreateLicenseLeaseRequest) validateNotAfter(formats strfmt.Registry) error {

	if err := validate.Required("NotAfter", "body", m.NotAfter); err != nil {
		return err
	}

	return nil
}

func (m *ModelsCreateLicenseLeaseRequest) validateNotBefore(formats strfmt.Registry) error {

	if err := validate.Required("NotBefore", "body", m.NotBefore); err != nil {
		return err
	}

	return nil
}

func (m *ModelsCreateLicenseLeaseRequest) validateVcpu(formats strfmt.Registry) error {

	if err := validate.Required("Vcpu", "body", m.Vcpu); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this models create license lease request based on context it is used
func (m *ModelsCreateLicenseLeaseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsCreateLicenseLeaseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsCreateLicenseLeaseRequest) UnmarshalBinary(b []byte) error {
	var res ModelsCreateLicenseLeaseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
