// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsActivateLicenseRequest models activate license request
//
// swagger:model models.ActivateLicenseRequest
type ModelsActivateLicenseRequest struct {

	// bundle
	// Required: true
	Bundle *string `json:"bundle"`

	// dry run
	// Required: true
	DryRun *bool `json:"dryRun"`

	// license
	// Required: true
	License *string `json:"license"`

	// override
	// Required: true
	Override *bool `json:"override"`
}

// Validate validates this models activate license request
func (m *ModelsActivateLicenseRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBundle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDryRun(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLicense(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOverride(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsActivateLicenseRequest) validateBundle(formats strfmt.Registry) error {

	if err := validate.Required("bundle", "body", m.Bundle); err != nil {
		return err
	}

	return nil
}

func (m *ModelsActivateLicenseRequest) validateDryRun(formats strfmt.Registry) error {

	if err := validate.Required("dryRun", "body", m.DryRun); err != nil {
		return err
	}

	return nil
}

func (m *ModelsActivateLicenseRequest) validateLicense(formats strfmt.Registry) error {

	if err := validate.Required("license", "body", m.License); err != nil {
		return err
	}

	return nil
}

func (m *ModelsActivateLicenseRequest) validateOverride(formats strfmt.Registry) error {

	if err := validate.Required("override", "body", m.Override); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this models activate license request based on context it is used
func (m *ModelsActivateLicenseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsActivateLicenseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsActivateLicenseRequest) UnmarshalBinary(b []byte) error {
	var res ModelsActivateLicenseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
