// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsQuotaUsage models quota usage
//
// swagger:model models.QuotaUsage
type ModelsQuotaUsage struct {

	// quota
	// Required: true
	Quota *ModelsLicenseQuota `json:"Quota"`

	// total
	// Required: true
	Total *int64 `json:"Total"`

	// used
	// Required: true
	Used *int64 `json:"Used"`
}

// Validate validates this models quota usage
func (m *ModelsQuotaUsage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuota(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsed(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsQuotaUsage) validateQuota(formats strfmt.Registry) error {

	if err := validate.Required("Quota", "body", m.Quota); err != nil {
		return err
	}

	if m.Quota != nil {
		if err := m.Quota.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("Quota")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("Quota")
			}

			return err
		}
	}

	return nil
}

func (m *ModelsQuotaUsage) validateTotal(formats strfmt.Registry) error {

	if err := validate.Required("Total", "body", m.Total); err != nil {
		return err
	}

	return nil
}

func (m *ModelsQuotaUsage) validateUsed(formats strfmt.Registry) error {

	if err := validate.Required("Used", "body", m.Used); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this models quota usage based on the context it is used
func (m *ModelsQuotaUsage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateQuota(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsQuotaUsage) contextValidateQuota(ctx context.Context, formats strfmt.Registry) error {

	if m.Quota != nil {

		if err := m.Quota.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("Quota")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("Quota")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsQuotaUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsQuotaUsage) UnmarshalBinary(b []byte) error {
	var res ModelsQuotaUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
